### PR TITLE
Setting supervisor_visit to null when value is null or undefined, #25

### PR DESCRIPTION
**Pull request by lakhassane**

### CODE REVIEW

**Review by taylordowns2000 — CHANGES_REQUESTED** [review]
seems to be missing the new linting (singlequote, no parens around single arg). also, how about:
```js
field('Supervisor_Visit__c', state => state.supervisorMap[state.data.form.supervisor_visit] || null),
```

the bigger question may be for @aleksa-krolls — why is this being set to `null`? Is it that you don't want a type error, or that this `null` value does something special in Salesforce? Given my understanding of the current implementation, it will be undefined and _left out_ of the payload that gets sent to SF without error. Is this change really necessary?

**Comment by lakhassane** [comment]
@taylordowns2000 yup the `.prettierrc` is missing from this branch since the styling has not been merged with `master` yet.

Once this PR is solved (with the answer from AK) and merged with `master`, I might repull from master and redo the styling.

**Comment by aleksa-krolls** [comment]
@lakhassane Please return `undefined` to Salesforce, if CommCare `supervisor_visit` is null or undefined? (And ensure no type error). Sorry for any confusion!

**Review by taylordowns2000 — COMMENTED** [review]
Rejecting as this doesn't actually change the behaviour and adds complexity, @aleksa-krolls .

**Pull request closed without merging**
