### PR TITLE
Changed CommCare_Code__c to Service_UID__c to align Service IDs for u…

### PR DESCRIPTION
**Pull request by ritazagoni**
…pdates across jobs

ID aligned with https://github.com/OpenFn/lwala/blob/16e8c371712f9c5b2245456cfaf61e55b6474213/commcare-salesforce-jobs/Update-Person-in-SF-Production.js#L418-L426 and https://github.com/OpenFn/lwala/blob/16e8c371712f9c5b2245456cfaf61e55b6474213/commcare-salesforce-jobs/MOH514-Update-Person-in-SF-Production.js#L967-L978

### CODE REVIEW

**Comment by aleksa-krolls** [comment]
@ritazagoni Hold off on merging please. 

I see that in your commit we're now using `Service_UID__c`... BUT if you look at the 2 Update Person Jobs, you'll see that Service_UID__c is a combination of both `case_id` AND `date` of whichever service is being referred.

Therefore, I'm wondering does the state for this `CHW Update` job also include the `date` for when the Service was scheduled? (If yes, then we can append this `date` to `case_id` to create a new `Service_UID__c`. If not, then we'll want to discuss with Beth and maybe wait until the new workflow is decided before we make any changes here.)

**Comment by ritazagoni** [comment]
There is no Service in CHW Update messages, only:
`"Case_Type": "Follow-Up",` // this can also be Referral
`"Date_Seen": "2021-09-29",`

I can use the `"Date_Seen"` with the `case_id`.

**Comment by aleksa-krolls** [comment]
@ritazagoni I don't think adding `date_seen` will add any value... the result will still be creating 1 new Service (rather than updating the original Service created). 

Therefore, I think we should hold on merging this change until Lwala has decided how to handle follow ups... I imagine there will be a different state we are working with then. But thank you for taking a closer look... can you link to this PR and put this issue on pause? We'll come back to it when Lwala has decided a way forward.

**Review by aleksa-krolls — CHANGES_REQUESTED** [review]
Not updating until Lwala advises on next steps for referral follow-ups.

**Pull request closed without merging**
